name: Keep Alive

on:
  schedule:
    - cron: "0 0 1 * *" # 1st of every month

permissions:
  contents: write

jobs:
  keepalive:
    runs-on: ubuntu-latest
    steps:
      - uses: gautamkrishnar/keepalive-workflow@v2
